### PR TITLE
Single responsability

### PR DESCRIPTION
**Pull request by lenonleite**
Resolved problem of Single responsability and adjust and insert more tests

### CODE REVIEW

**Comment by leonnleite** [comment]
@lenonleite do you have issues, fix it please
see the travis report

**Comment by leonnleite** [comment]
@lenonleite 
Rly?
you broke your project, do you need more responsibility.
You ignore my comment, ignore the travis report. 

I give up.

**Comment by abdala** [comment]
We have to be more careful when merging a PR. A broken PR can never be merged. ;)

**Comment by lenonleite** [comment]
Sorry brother, I am learning about travis. Travis is recent for me. Have a more patient, please.

**Pull request merged**
